# Generated by Django 6.0.4 on 2026-05-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_doctor_service_service_doctor"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="duration",
            field=models.IntegerField(default=30),
        ),
    ]
